<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\DirectoryService.Contracts\DirectoryService.Contracts.csproj" />
      <ProjectReference Include="..\DirectoryService.Domain\DirectoryService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.72" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
      <PackageReference Include="Scrutor" Version="7.0.0" />
      <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\Departments\Commands\" />
      <Folder Include="Features\Locations\Commands\" />
    </ItemGroup>

</Project>
